name: it_news
description: IT News Mobile App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  avatar_view: ^1.0.1
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_swipe_action_cell: ^2.1.6
  formz: ^0.4.1
  google_nav_bar: ^5.0.5
  highlight: ^0.7.0
  http: ^0.13.4
  hydrated_bloc: ^8.0.0
  intl: ^0.17.0
  loading_animation_widget: ^1.0.0+1
  loading_indicator: ^3.0.2
  markdown_widget: ^1.2.7
  path_provider: ^2.0.8
  scroll_navigation: ^1.3.2
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
